### ISSUE TITLE
write EPROTO in geolocation example

### ISSUE THREAD

**Issue by needforspeed** [vercel/examples#83] opened 2022-01-21 16:04 UTC
I created app with the command

```bash
npx create-next-app --example https://github.com/vercel/examples/tree/main/edge-functions/geolocation <my_project_name>
```

Then start it with `npm run dev` in the my_project_name directory

When I hit the localhost:3000, I see the error in console
```
error - Error: write EPROTO 281473417277456:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

node version: v16.13.2
npm version: 8.1.2

**Comment by lfades** [comment] 2023-01-24 03:26
I can't reproduce this issue so I'm closing it for now, it's also likely the issue no longer exists today as this was 1 year ago. If the issue persists please lmk 🙏

**Closed by lfades** 2023-01-24 03:26 UTC
Labels: needs investigation
