### ISSUE TITLE
Unhandled Runtime Error, incompatible-href-as

### ISSUE THREAD

**Issue by moinulmoin** [vercel/examples#55] opened 2021-12-06 15:03 UTC
**Unhandled Runtime Error**
Error: The provided `as` value (/) is incompatible with the `href` value (/_sites/[site]). Read more: https://nextjs.org/docs/messages/incompatible-href-as

https://github.com/vercel/examples/tree/main/edge-functions/hostname-rewrites
**I just cloned this repo and tried to run it on my local and I am facing this error:**

![image](https://user-images.githubusercontent.com/63459189/144869265-cdaa695e-e774-4f54-9e3b-60cd35b109e0.png)

How to solve it. I haven't found any solution!

Thank in advance

**Comment by JohnAllen** [comment] 2021-12-07 14:59
I can't solve it without having the code. I know what it is about but not sure exactly where the error is.

**Comment by moinulmoin** [comment] 2021-12-07 15:02
I just simply followed the steps which are in readme.md then I am getting this error. Could you please give a check now by following steps? thanks

**Comment by jonspark** [comment] 2021-12-07 20:14
I'm coming up with the same issue with a fresh project based on the example. This line is the only reference to a `href="/"` https://github.com/vercel/examples/blob/ec0cfc9bb150380683010d6c5e14dbadadd31c0a/edge-functions/hostname-rewrites/pages/_sites/%5Bsite%5D/index.tsx#L28

There's a similar issue if you visit the About page but the value is `/about`.

<img width="1261" src="https://user-images.githubusercontent.com/750051/145099294-e0b5d5f6-eaa9-4643-b9a2-3ff7d1d99a5d.png" alt="NextJS error message stating: Unhandled runtime error - Error: The provided `as` value (/about) is incompatible with the `href` value (/_sites/[site]/about). Read more: https://nextjs.org/docs/messages/incompatible-href-as">

**Comment by StitiFatah** [comment] 2021-12-08 14:19
Same here, but only in certain conditions : 

- Dev Server + exported getStaticProps : **no problem** 
- Dev Server + no getStaticProps : *same error as OP's*
- Prod Server : **no error whether using dev or prod server**

**Comment by moinulmoin** [comment] 2021-12-10 15:35
@JohnAllen Could you please help us, man? thank you

**Comment by JohnAllen** [comment] 2021-12-10 15:39
Just change the value of that. What have you tried? Remove it altogether.

**Comment by StitiFatah** [comment] 2021-12-10 16:30
I don't think it has anything to do with the href, I don't have any <Link/> or <a/> in my code.

**Comment by moinulmoin** [comment] 2021-12-12 19:51
@JohnAllen ain't you maintaining this example repo?

**Comment by JohnAllen** [comment] 2021-12-12 20:19
LOL what makes you think that? Hahahahah

**Comment by JohnAllen** [comment] 2021-12-12 20:27
Excellent usage of "ain't" as well.

**Comment by moinulmoin** [comment] 2021-12-13 06:12
> LOL what makes you think that? Hahahahah @moinulmoin

Haha, don't know. I thought you were maintaining this example repo. My bad! then where are official authors/maintainers? we need help regarding this issue 😣

**Comment by StitiFatah** [comment] 2021-12-13 15:56
> @steven-tey help please!

I have created a new issue on NectJs repos https://github.com/vercel/next.js/issues/32446

**Comment by balazsorban44** [comment] 2021-12-14 00:20
To whom it may concern, please keep the discussion to the point!

**Comment by akinwol** [comment] 2022-01-11 05:49
@StitiFatah @moinulmoin  it's because you don't have corresponding mock data simply adding this to the mock data will solve
`
 {
    name: 'Site 4',
    description: 'Host One',
    subdomain: 'hostname-1',
    customDomain: null,
  },
`

**Comment by StitiFatah** [comment] 2022-01-11 10:57
> @StitiFatah @moinulmoin it's because you don't have corresponding mock data simply adding this to the mock data will solve `{ name: 'Site 4', description: 'Host One', subdomain: 'hostname-1', customDomain: null, },`

Hey mate, having it working without adding the corresponding data is the whole the point of the issue, this piece of code 

```
export default function NewPage({ domain }) {
  return <div> New Page {domain} </div>;
}
```

Should return in the browser `NewPage subdomain_used`  whether or not the subdomain is in the mockDB. If it  is already in the mockDB and the path has already been generated generated it's already fine else `fallback:true` or `fallback:"blocking"` should play their roles and re run `getStaticProps` to the subdomain value. 

For proof the whole process is perfectly working when setting `fallback` to "blocking" but with `fallback:true` it triggers the error.

Example :  I visit `domain-1.localhost:3000/newpage/`, since the `domain-1` subdomain is already in the mockDB it works. But now if I visit    domain-25.localhost:3000/newpage/` it works perfectly with `fallback:"blocking"` but not  with`fallback:true` but it should normally work with both.

**Comment by StitiFatah** [comment] 2022-01-11 11:18
Hi again, the issue is solved for me and everything is working with `fallback:true` and even with CSR when using the lats canary version. #32446

**Comment by lfades** [comment] 2022-03-26 20:53
Closing as per the comment above, if the issue still persists please comment again and it'll re-open it.

**Closed by lfades** 2022-03-26 20:53 UTC
Labels: needs investigation
