### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by elie222** [vercel/examples#302] opened 2022-06-16 16:00 UTC
When running the cdk example the following error occurs when running cdk bootstrap:

```
import 'source-map-support/register';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by dominiksipowicz** [comment] 2022-06-17 08:38
hey @elie222 can you provide more information about your setup:
1. output of `npx next info`
2. did you used `npm` or `yarn`?

Maybe @GuiBibeau @leerob can help here because this is the [AWS S3 image example](https://github.com/vercel/examples/tree/main/solutions/aws-s3-image-upload), right?

This PR #296 was also merged after your issue was created.

**Comment by leerob** [comment] 2022-06-17 14:06
It could be related to the version of Node.js you're using (guess).

**Comment by lofsigma** [comment] 2022-06-28 14:36
I also ran into a similar issue use, tried both npm and yarn.
`    Operating System:
      Platform: darwin
      Arch: x64
      Node: 18.4.0
      npm: 8.12.1
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0`

**Comment by veryserious** [comment] 2022-08-18 06:41
Same issue with output of `npx next info`

`    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.4
      eslint-config-next: 12.2.4
      react: 18.2.0
      react-dom: 18.2.0`

**Comment by mkayander** [comment] 2022-09-10 18:49
Hey everyone. The issue is that AWS CDK typescript code requires a bit different tsconfig settings. You can find the details in the linked PR i just pushed.

**Closed** 2022-09-10 20:24 UTC
