### ISSUE TITLE
[Question] geolocation example is not working 

### ISSUE THREAD

**Issue by arendondiosa** [vercel/examples#34] opened 2021-11-07 13:17 UTC
Hi, I'm testing [this example](https://github.com/vercel/examples/tree/main/edge-functions/geolocation) but the result is the default values (see image)

![Screen Shot 2021-11-07 at 8 07 44](https://user-images.githubusercontent.com/14989202/140646450-0656a672-5ada-4f57-8a0e-49c989766132.png)

I used my local environment and the option to deploy using vercel.com (https://geolocation-beta.vercel.app/)

![Screen Shot 2021-11-07 at 8 16 22](https://user-images.githubusercontent.com/14989202/140646529-ed56e6a8-002a-4023-9845-2d0bce5e676e.png)

Is there any configuration required to make it work?

**Comment by judewang** [comment] 2021-11-09 06:26
I have the same issue, too. I followed the example and deployed it to Vercel, and I found `req.geo.country` was `undefined`.

**Comment by danestves** [comment] 2021-11-09 06:40
As i understand the geo object is available only for paid plans on Vercel

**Comment by judewang** [comment] 2021-11-09 07:51
@danestves WOW, I can confirm the example works correctly after I transferred it to my team project. Thank you.

**Comment by leerob** [comment] 2021-11-09 15:43
Duplicate of https://github.com/vercel/examples/issues/24.

We're making `geo` available for all plans this week, sorry about this! Was not intended.

**Closed by leerob** 2021-11-09 15:43 UTC

**Comment by armannaj** [comment] 2023-08-24 02:06
I have used request.geo on vercel and it is still empty and undefined. Although the header["x-vercel-ip-country"] is populated, but the objects (ip and geo) are still empty on vercel.
